version: '3.3'

services:
  server:
    build: ./services/server/
    volumes:
      - ./services/server/:/app
    command: "npm run start:dev"
    ports:
      - 8000:8000
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: workahomie
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data/workahomie/mongo:/data/db
