export const OCCUPATIONS = [
  'accountant',
  'architect',
  'artist',
  'business analyst',
  'consultant',
  'data scientist',
  'doctor',
  'engineer',
  'environmental scientist',
  'filmmaker',
  'graphic designer',
  'illustrator',
  'lawyer',
  'marketing specialist',
  'musician',
  'photographer',
  'product manager',
  'project manager',
  'sales representative',
  'scientist',
  'software developer',
  'teacher/tutor',
  'ui/ux designer',
  'videographer',
  'virtual assistant',
  'writer',
  'others',
];
