export const OCCUPATIONS = [
  'Accountant',
  'Architect',
  'Artist',
  'Business Analyst',
  'Consultant',
  'Data Scientist',
  'Doctor',
  'Engineer',
  'Environmental Scientist',
  'Filmmaker',
  'Graphic Designer',
  'Illustrator',
  'Lawyer',
  'Marketing Specialist',
  'Musician',
  'Photographer',
  'Product Manager',
  'Project Manager',
  'Sales Representative',
  'Scientist',
  'Software Developer',
  'Teacher/Tutor',
  'UI/UX Designer',
  'Videographer',
  'Virtual Assistant',
  'Writer',
  'Others',
];
