import { IconType } from 'react-icons';
import {
  FaCode,
  FaPaintBrush,
  FaChartLine,
  FaMusic,
  FaPen,
  FaFilm,
  FaPalette,
  FaDatabase,
  FaTasks,
  FaDraftingCompass,
  FaCameraRetro,
  FaCalculator,
  FaUserTie,
  FaFlask,
  FaCogs,
  FaChalkboardTeacher,
  FaProjectDiagram,
  FaHandshake,
  FaLightbulb,
  FaPencilRuler,
  FaVideo,
  FaBriefcase,
  FaBalanceScale,
  FaHeartbeat,
  FaLeaf,
  FaObjectGroup,
  FaQuestionCircle,
} from 'react-icons/fa';

export type Occupation = {
  name: string;
  icon: IconType;
};

export const OCCUPATIONS: Occupation[] = [
  { name: 'Accountant', icon: FaCalculator },
  { name: 'Architect', icon: FaDraftingCompass },
  { name: 'Artist', icon: FaPaintBrush },
  { name: 'Business Analyst', icon: FaLightbulb },
  { name: 'Consultant', icon: FaUserTie },
  { name: 'Data Scientist', icon: FaDatabase },
  { name: 'Doctor', icon: FaHeartbeat },
  { name: 'Engineer', icon: FaCogs },
  { name: 'Environmental Scientist', icon: FaLeaf },
  { name: 'Filmmaker', icon: FaFilm },
  { name: 'Graphic Designer', icon: FaPalette },
  { name: 'Illustrator', icon: FaPencilRuler },
  { name: 'Lawyer', icon: FaBalanceScale },
  { name: 'Marketing Specialist', icon: FaChartLine },
  { name: 'Musician', icon: FaMusic },
  { name: 'Photographer', icon: FaCameraRetro },
  { name: 'Product Manager', icon: FaTasks },
  { name: 'Project Manager', icon: FaProjectDiagram },
  { name: 'Sales Representative', icon: FaHandshake },
  { name: 'Scientist', icon: FaFlask },
  { name: 'Software Developer', icon: FaCode },
  { name: 'Teacher/Tutor', icon: FaChalkboardTeacher },
  { name: 'UI/UX Designer', icon: FaObjectGroup },
  { name: 'Videographer', icon: FaVideo },
  { name: 'Virtual Assistant', icon: FaBriefcase },
  { name: 'Writer', icon: FaPen },
  { name: 'Others', icon: FaQuestionCircle },
];
